### ISSUE TITLE
Remove Run: command from command links

### ISSUE THREAD

**Issue by oblx** [DosMike/WebBooks#1]
Oh hi !

It's been a while, are you doing good ?
I would like to know if it's possible to remove the `Run: command` part for command links (but well, it's the title of the ticket).

I could achieve a great feature for my server : https://imgur.com/a/yibRQX0
It's both displayed ingame and on the website, exact same aspect and navigation. Just not optimised for mobile at all.

If you are busy, no trouble, it's already convenient enough for my use :)

Stay safe !

**Comment by Valandur** [comment]
I'm not sure I have control over that, it may be something done by Sponge/Minecraft. I'll have to take a look at it :+1:

**Comment by oblx** [comment]
Thanks, I can't wait to see :)

However, did you and dosMike team up for development purposes ?

**Comment by DosMike** [comment]
(just for completion)
i think this was possible before, but with 1.2 the config has an option and the data-title-hide-href attribute hides it on single links
